[theme]
theme =  "solarized-dark"

[icons]
icons = "awesome4"

[[block]]
block = "custom"
interval = "once"
command = "echo ' Run'"
hide_when_empty = false
[[block.click]]
button = "left"
cmd = "i3-dmenu-desktop"

[[block]]
block = "custom"
command = "~/.config/sway/scripts/get_keyboard_layout.sh"
interval = 0.2

[[block]]
block = "sound"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
device = "enp2s0"
format = "$icon $ssid ↑speed_up ↓$speed_down"
interval = 5

[[block]]
block = "net"
device = "wlan0"
format = "$icon $ssid "
interval = 5
[[block.click]]
button = "right"
cmd = "~/.config/sway/scripts/show_notification.sh wifi"
[[block.click]]
button="left"
cmd = "nm-connection-editor"

[[block]]
block = "battery"
device = "BAT1"
format = "$icon $percentage $time"
interval = 5

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d %b %R') "

[[block]]
block = "custom"
command = "echo \uf011 "
interval = "once"
[[block.click]]
button = "left"
cmd = "~/.config/sway/scripts/dmenu-logout.sh"

